sudo: required
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install .
  - pip install codecov pytest pytest-cov

script: python -m pytest --cov=website_fewo .


after_success:
  - codecov

notifications:
  email:
    recipients:
      - philipp_ehm@protonmail.com
    on_success: never
    on_failure: always